version: '3.9'

services:
  app:
    restart: always
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=secret_key
      - DEBUG=True
      - HOST=0.0.0.0
      - DB_NAME=flaskdev_db
      - DB_HOST=db
      - DB_PASSWORD=flaskdev_pass
      - DB_USER=flaskdev
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:14.6-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flaskdev_db
      - POSTGRES_USER=flaskdev
      - POSTGRES_PASSWORD=flaskdev_pass
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d flaskdev_db -U flaskdev"]
        interval: 2s
        timeout: 5s
        retries: 5

  test_db:
    image: postgres:14.6-alpine
    restart: always
    volumes:
      - test-db-data:/var/lib/postgresql/test-data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password

volumes:
  dev-db-data:
  test-db-data: