---
name: Checks
 
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        env:
          SECRETS: ${{secrets.TESTS_SECRETS}}
        run: |
          printf ${{env.SECRETS}} >> app/.env
      - name: Test
        run: |
          docker-compose --env-file app/.env up -d
          sleep 5
          docker-compose --env-file app/.env run --rm app sh -c "pytest"
          docker-compose stop
      - name: Formating
        run: docker-compose --env-file app/.env run --rm app sh -c "flake8"